security:
    password_hashers:
        Symfony\Component\Security\Core\User\PasswordAuthenticatedUserInterface: 'auto'

    providers:
        app_user_provider:
            entity:
                class: App\Entity\User
                property: email

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider


            # Form login
            form_login:
                login_path: app_login
                check_path: app_login
                enable_csrf: true
                default_target_path: ^/

            # Custom authenticator
            custom_authenticator: App\Security\AppAuthenticator

            # Définit le point d'entrée pour les utilisateurs anonymes
            entry_point: form_login

            # Logout
            logout:
                path: app_logout

            # Remember me
            remember_me:
                secret: '%kernel.secret%'
                lifetime: 604800
                path: /

    access_control:
        - path: ^/admin
          roles: ROLE_ADMIN






    role_hierarchy:
        ROLE_AUTHOR: ROLE_USER
        ROLE_ADMIN: [ ROLE_AUTHOR, ROLE_USER ]
